import { ConnectorManifest } from '@automation/shared-types';

export const githubManifest: ConnectorManifest = {
  id: 'github',
  name: 'GitHub',
  description:
    'Full GitHub integration — manage repositories, branches, files, issues, pull requests, releases, Actions workflows, and collaborators via GitHub REST API v3.',
  category: 'Developer Tools',
  icon: '/icons/github.svg',
  authType: 'api_key',
  authConfig: {
    fields: [
      {
        key: 'personalAccessToken',
        label: 'Personal Access Token (PAT)',
        type: 'password',
        required: true,
        description:
          'Generate at GitHub → Settings → Developer settings → Personal access tokens. Required scopes depend on actions used (repo, workflow, admin:repo_hook).',
      },
      {
        key: 'username',
        label: 'GitHub Username or Org',
        type: 'string',
        required: true,
        description: 'Your GitHub username or organization name (e.g. octocat).',
      },
    ],
  },
  authScopes: ['repo', 'workflow', 'admin:repo_hook', 'read:user'],
  docsUrl: 'https://docs.github.com/en/rest',
  version: '1.0.0',

  // ─── Triggers ──────────────────────────────────────────────────────────────
  triggers: [
    {
      id: 'new_repo_created',
      name: 'New Repository Created',
      description: 'Fires when a new repository is created in your account or organization.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      requiredScopes: ['admin:repo_hook'],
      inputs: [
        { key: 'repoName', label: 'Repository Name', type: 'string', required: false, hasDynamicChoices: true, choicesFieldId: 'repoName', description: 'Leave blank to watch all repositories.' },
      ],
      outputs: [
        { key: 'repoId', label: 'Repository ID', type: 'number', required: true },
        { key: 'repoName', label: 'Repository Name', type: 'string', required: true },
        { key: 'fullName', label: 'Full Name (owner/repo)', type: 'string', required: true },
        { key: 'htmlUrl', label: 'Repository URL', type: 'string', required: true },
        { key: 'private', label: 'Is Private', type: 'boolean', required: true },
        { key: 'defaultBranch', label: 'Default Branch', type: 'string', required: true },
        { key: 'description', label: 'Description', type: 'string', required: false },
        { key: 'createdAt', label: 'Created At', type: 'string', required: true },
        { key: 'ownerLogin', label: 'Owner Login', type: 'string', required: true },
      ],
    },
    {
      id: 'new_commit_pushed',
      name: 'New Commit Pushed',
      description: 'Fires when one or more commits are pushed to any branch of the repository.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      requiredScopes: ['repo'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'branchFilter', label: 'Branch Filter (optional, e.g. main)', type: 'string', required: false },
      ],
      outputs: [
        { key: 'commitSha', label: 'Commit SHA', type: 'string', required: true },
        { key: 'commitMessage', label: 'Commit Message', type: 'string', required: true },
        { key: 'authorName', label: 'Author Name', type: 'string', required: true },
        { key: 'authorEmail', label: 'Author Email', type: 'string', required: true },
        { key: 'branch', label: 'Branch Name', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository Full Name', type: 'string', required: true },
        { key: 'timestamp', label: 'Commit Timestamp', type: 'string', required: true },
        { key: 'commitUrl', label: 'Commit URL', type: 'string', required: true },
        { key: 'commits', label: 'All Commits (array)', type: 'array', required: true },
        { key: 'pusherName', label: 'Pusher Username', type: 'string', required: true },
      ],
    },
    {
      id: 'new_branch_created',
      name: 'New Branch Created',
      description: 'Fires when a new branch is created in the repository.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
      ],
      outputs: [
        { key: 'branchName', label: 'Branch Name', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
        { key: 'sha', label: 'HEAD Commit SHA', type: 'string', required: true },
        { key: 'createdBy', label: 'Created By', type: 'string', required: true },
      ],
    },
    {
      id: 'new_pr_opened',
      name: 'Pull Request Opened',
      description: 'Fires when a new pull request is opened.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
      ],
      outputs: [
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
        { key: 'prTitle', label: 'PR Title', type: 'string', required: true },
        { key: 'prBody', label: 'PR Description', type: 'string', required: false },
        { key: 'authorLogin', label: 'Author Username', type: 'string', required: true },
        { key: 'headBranch', label: 'Source Branch', type: 'string', required: true },
        { key: 'baseBranch', label: 'Target Branch', type: 'string', required: true },
        { key: 'htmlUrl', label: 'PR URL', type: 'string', required: true },
        { key: 'draft', label: 'Is Draft', type: 'boolean', required: true },
        { key: 'labels', label: 'Labels (array)', type: 'array', required: false },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
      ],
    },
    {
      id: 'pr_merged',
      name: 'Pull Request Merged',
      description: 'Fires when a pull request is successfully merged.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
        { key: 'prTitle', label: 'PR Title', type: 'string', required: true },
        { key: 'mergedBy', label: 'Merged By', type: 'string', required: true },
        { key: 'mergedAt', label: 'Merged At', type: 'string', required: true },
        { key: 'headBranch', label: 'Source Branch', type: 'string', required: true },
        { key: 'baseBranch', label: 'Target Branch', type: 'string', required: true },
        { key: 'mergeCommitSha', label: 'Merge Commit SHA', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
      ],
    },
    {
      id: 'pr_closed',
      name: 'Pull Request Closed (Without Merge)',
      description: 'Fires when a pull request is closed without being merged.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
        { key: 'prTitle', label: 'PR Title', type: 'string', required: true },
        { key: 'closedBy', label: 'Closed By', type: 'string', required: true },
        { key: 'closedAt', label: 'Closed At', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
      ],
    },
    {
      id: 'new_issue_created',
      name: 'New Issue Created',
      description: 'Fires when a new issue is opened in the repository.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'issueTitle', label: 'Issue Title', type: 'string', required: true },
        { key: 'issueBody', label: 'Issue Body', type: 'string', required: false },
        { key: 'authorLogin', label: 'Author Username', type: 'string', required: true },
        { key: 'labels', label: 'Labels (array)', type: 'array', required: false },
        { key: 'assignees', label: 'Assignees (array)', type: 'array', required: false },
        { key: 'htmlUrl', label: 'Issue URL', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
        { key: 'createdAt', label: 'Created At', type: 'string', required: true },
      ],
    },
    {
      id: 'issue_updated',
      name: 'Issue Updated',
      description: 'Fires when an existing issue is edited, labeled, assigned, or milestoned.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'action', label: 'Action (edited/labeled/assigned)', type: 'string', required: true },
        { key: 'issueTitle', label: 'Issue Title', type: 'string', required: true },
        { key: 'updatedAt', label: 'Updated At', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
      ],
    },
    {
      id: 'issue_closed',
      name: 'Issue Closed',
      description: 'Fires when an issue is closed.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'issueTitle', label: 'Issue Title', type: 'string', required: true },
        { key: 'closedBy', label: 'Closed By', type: 'string', required: true },
        { key: 'closedAt', label: 'Closed At', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
      ],
    },
    {
      id: 'new_issue_comment',
      name: 'New Issue Comment',
      description: 'Fires when someone comments on an issue.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'commentBody', label: 'Comment Text', type: 'string', required: true },
        { key: 'commentAuthor', label: 'Comment Author', type: 'string', required: true },
        { key: 'commentUrl', label: 'Comment URL', type: 'string', required: true },
        { key: 'commentId', label: 'Comment ID', type: 'number', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
      ],
    },
    {
      id: 'new_pr_comment',
      name: 'New PR Review Comment',
      description: 'Fires when a review comment is added to a pull request.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
        { key: 'commentBody', label: 'Comment Text', type: 'string', required: true },
        { key: 'commentAuthor', label: 'Comment Author', type: 'string', required: true },
        { key: 'diffHunk', label: 'Diff Hunk Context', type: 'string', required: false },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
      ],
    },
    {
      id: 'new_release_published',
      name: 'Release Published',
      description: 'Fires when a new release is published (not draft or pre-release unless specified).',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'tagName', label: 'Tag Name (e.g. v1.2.0)', type: 'string', required: true },
        { key: 'releaseName', label: 'Release Name', type: 'string', required: true },
        { key: 'releaseBody', label: 'Release Notes', type: 'string', required: false },
        { key: 'htmlUrl', label: 'Release URL', type: 'string', required: true },
        { key: 'prerelease', label: 'Is Pre-release', type: 'boolean', required: true },
        { key: 'draft', label: 'Is Draft', type: 'boolean', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
        { key: 'publishedAt', label: 'Published At', type: 'string', required: true },
      ],
    },
    {
      id: 'workflow_run_completed',
      name: 'GitHub Actions Workflow Completed',
      description: 'Fires when a GitHub Actions workflow run finishes (success, failure, or cancelled).',
      type: 'trigger',
      deliveryMethod: 'webhook',
      requiredScopes: ['repo', 'workflow'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'workflowName', label: 'Workflow Name Filter (optional)', type: 'string', required: false },
      ],
      outputs: [
        { key: 'workflowName', label: 'Workflow Name', type: 'string', required: true },
        { key: 'conclusion', label: 'Conclusion (success/failure/cancelled)', type: 'string', required: true },
        { key: 'runId', label: 'Run ID', type: 'number', required: true },
        { key: 'runUrl', label: 'Run URL', type: 'string', required: true },
        { key: 'branch', label: 'Branch', type: 'string', required: true },
        { key: 'event', label: 'Triggering Event', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
        { key: 'startedAt', label: 'Started At', type: 'string', required: true },
        { key: 'completedAt', label: 'Completed At', type: 'string', required: true },
      ],
    },
    {
      id: 'new_collaborator_added',
      name: 'Collaborator Added',
      description: 'Fires when a new collaborator is added to the repository.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      requiredScopes: ['admin:repo_hook'],
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'login', label: 'Collaborator Username', type: 'string', required: true },
        { key: 'permission', label: 'Permission Level', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
      ],
    },
    {
      id: 'new_star',
      name: 'Repository Starred',
      description: 'Fires when someone stars the repository.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'starredBy', label: 'Starred By', type: 'string', required: true },
        { key: 'starredAt', label: 'Starred At', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
        { key: 'stargazersCount', label: 'Total Stars', type: 'number', required: true },
      ],
    },
    {
      id: 'new_fork',
      name: 'Repository Forked',
      description: 'Fires when someone forks the repository.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'forkOwner', label: 'Fork Owner', type: 'string', required: true },
        { key: 'forkRepoName', label: 'Fork Repository Name', type: 'string', required: true },
        { key: 'forkHtmlUrl', label: 'Fork URL', type: 'string', required: true },
        { key: 'repoFullName', label: 'Original Repository', type: 'string', required: true },
      ],
    },
    {
      id: 'deployment_status_changed',
      name: 'Deployment Status Changed',
      description: 'Fires when a deployment status changes (pending, success, failure, error).',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [{ key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' }],
      outputs: [
        { key: 'environment', label: 'Environment', type: 'string', required: true },
        { key: 'state', label: 'State (pending/success/failure/error)', type: 'string', required: true },
        { key: 'deploymentUrl', label: 'Deployment URL', type: 'string', required: false },
        { key: 'description', label: 'Status Description', type: 'string', required: false },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
        { key: 'createdAt', label: 'Created At', type: 'string', required: true },
      ],
    },
    {
      id: 'new_push',
      name: 'New Push to Branch',
      description: 'Fires on any push event. Includes all commits in the push.',
      type: 'trigger',
      deliveryMethod: 'webhook',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'branchFilter', label: 'Branch Filter (optional)', type: 'string', required: false },
      ],
      outputs: [
        { key: 'branch', label: 'Branch', type: 'string', required: true },
        { key: 'commits', label: 'Commits Array', type: 'array', required: true },
        { key: 'pusherName', label: 'Pusher Name', type: 'string', required: true },
        { key: 'repoFullName', label: 'Repository', type: 'string', required: true },
        { key: 'compareUrl', label: 'Compare URL', type: 'string', required: true },
        { key: 'forced', label: 'Was Force Push', type: 'boolean', required: true },
      ],
    },
  ],

  // ─── Actions ───────────────────────────────────────────────────────────────
  actions: [
    // ── Repositories ──
    {
      id: 'create_repo',
      name: 'Create Repository',
      description: 'Creates a new repository under the authenticated user or organization.',
      type: 'action',
      httpMethod: 'POST',
      endpoint: '/user/repos',
      requiredScopes: ['repo'],
      inputs: [
        { key: 'name', label: 'Repository Name', type: 'string', required: true },
        { key: 'description', label: 'Description', type: 'string', required: false },
        { key: 'private', label: 'Private Repository', type: 'boolean', required: false, description: 'Default: false (public)' },
        { key: 'autoInit', label: 'Initialize with README', type: 'boolean', required: false },
        { key: 'gitignoreTemplate', label: '.gitignore Template (e.g. Node)', type: 'string', required: false },
        { key: 'org', label: 'Organization (optional)', type: 'string', required: false, description: 'Creates under org instead of user account' },
      ],
      outputs: [
        { key: 'repoId', label: 'Repository ID', type: 'number', required: true },
        { key: 'fullName', label: 'Full Name (owner/repo)', type: 'string', required: true },
        { key: 'htmlUrl', label: 'Repository URL', type: 'string', required: true },
        { key: 'cloneUrl', label: 'Clone URL', type: 'string', required: true },
        { key: 'defaultBranch', label: 'Default Branch', type: 'string', required: true },
        { key: 'private', label: 'Is Private', type: 'boolean', required: true },
      ],
      rateLimitInfo: { requestsPerHour: 5000, notes: 'GitHub API rate limit: 5,000 requests/hour for authenticated requests.' },
    },
    {
      id: 'update_repo',
      name: 'Update Repository Settings',
      description: 'Updates settings of an existing repository (name, description, visibility, etc.).',
      type: 'action',
      httpMethod: 'PATCH',
      endpoint: '/repos/{owner}/{repo}',
      requiredScopes: ['repo'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'newName', label: 'New Repository Name', type: 'string', required: false },
        { key: 'description', label: 'Description', type: 'string', required: false },
        { key: 'private', label: 'Make Private', type: 'boolean', required: false },
        { key: 'defaultBranch', label: 'Default Branch', type: 'string', required: false },
        { key: 'hasIssues', label: 'Enable Issues', type: 'boolean', required: false },
        { key: 'hasWiki', label: 'Enable Wiki', type: 'boolean', required: false },
      ],
      outputs: [
        { key: 'fullName', label: 'Updated Full Name', type: 'string', required: true },
        { key: 'htmlUrl', label: 'Repository URL', type: 'string', required: true },
        { key: 'updatedAt', label: 'Updated At', type: 'string', required: true },
      ],
    },
    {
      id: 'delete_repo',
      name: 'Delete Repository',
      description: 'Permanently deletes a repository. This action is irreversible.',
      type: 'action',
      httpMethod: 'DELETE',
      endpoint: '/repos/{owner}/{repo}',
      requiredScopes: ['delete_repo'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName', description: '⚠ Irreversible. Repository and all data will be deleted.' },
      ],
      outputs: [
        { key: 'deleted', label: 'Was Deleted', type: 'boolean', required: true },
      ],
      rateLimitInfo: { notes: '⚠ WARNING: Permanently deletes repository and all data. Cannot be undone.' },
    },
    {
      id: 'list_repos',
      name: 'List Repositories',
      description: 'Lists repositories for the authenticated user or an organization.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/user/repos',
      inputs: [
        { key: 'type', label: 'Type', type: 'select', required: false, options: [{ label: 'All', value: 'all' }, { label: 'Owner', value: 'owner' }, { label: 'Public', value: 'public' }, { label: 'Private', value: 'private' }] },
        { key: 'sort', label: 'Sort By', type: 'select', required: false, options: [{ label: 'Updated', value: 'updated' }, { label: 'Created', value: 'created' }, { label: 'Full Name', value: 'full_name' }] },
        { key: 'perPage', label: 'Results Per Page (max 100)', type: 'number', required: false },
        { key: 'org', label: 'Organization (optional)', type: 'string', required: false },
      ],
      outputs: [
        { key: 'repos', label: 'Repositories Array', type: 'array', required: true },
        { key: 'count', label: 'Total Count', type: 'number', required: true },
      ],
    },
    {
      id: 'get_repo',
      name: 'Get Repository Info',
      description: 'Fetches full details of a specific repository.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
      ],
      outputs: [
        { key: 'repoId', label: 'Repository ID', type: 'number', required: true },
        { key: 'fullName', label: 'Full Name', type: 'string', required: true },
        { key: 'description', label: 'Description', type: 'string', required: false },
        { key: 'private', label: 'Is Private', type: 'boolean', required: true },
        { key: 'htmlUrl', label: 'URL', type: 'string', required: true },
        { key: 'stargazersCount', label: 'Stars', type: 'number', required: true },
        { key: 'forksCount', label: 'Forks', type: 'number', required: true },
        { key: 'openIssuesCount', label: 'Open Issues', type: 'number', required: true },
        { key: 'defaultBranch', label: 'Default Branch', type: 'string', required: true },
        { key: 'language', label: 'Primary Language', type: 'string', required: false },
        { key: 'createdAt', label: 'Created At', type: 'string', required: true },
        { key: 'updatedAt', label: 'Updated At', type: 'string', required: true },
      ],
    },
    // ── Branches ──
    {
      id: 'create_branch',
      name: 'Create Branch',
      description: 'Creates a new branch from a specified SHA or existing branch.',
      type: 'action',
      httpMethod: 'POST',
      endpoint: '/repos/{owner}/{repo}/git/refs',
      requiredScopes: ['repo'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'branchName', label: 'New Branch Name', type: 'string', required: true },
        { key: 'fromBranch', label: 'Base Branch or SHA', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'branchName', description: 'Branch name (e.g. main) or full commit SHA to branch from.' },
      ],
      outputs: [
        { key: 'branchName', label: 'Branch Name', type: 'string', required: true },
        { key: 'sha', label: 'Commit SHA', type: 'string', required: true },
        { key: 'ref', label: 'Full Ref', type: 'string', required: true },
      ],
    },
    {
      id: 'delete_branch',
      name: 'Delete Branch',
      description: 'Deletes a branch from the repository.',
      type: 'action',
      httpMethod: 'DELETE',
      endpoint: '/repos/{owner}/{repo}/git/refs/heads/{branch}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'branchName', label: 'Branch to Delete', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'branchName' },
      ],
      outputs: [{ key: 'deleted', label: 'Was Deleted', type: 'boolean', required: true }],
    },
    {
      id: 'list_branches',
      name: 'List Branches',
      description: 'Lists all branches in a repository.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/branches',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'perPage', label: 'Results Per Page (max 100)', type: 'number', required: false },
      ],
      outputs: [
        { key: 'branches', label: 'Branches Array', type: 'array', required: true },
        { key: 'count', label: 'Total Count', type: 'number', required: true },
      ],
    },
    {
      id: 'get_branch',
      name: 'Get Branch Info',
      description: 'Fetches details of a specific branch including its HEAD commit.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/branches/{branch}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'branchName', label: 'Branch', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'branchName' },
      ],
      outputs: [
        { key: 'name', label: 'Branch Name', type: 'string', required: true },
        { key: 'sha', label: 'HEAD Commit SHA', type: 'string', required: true },
        { key: 'commitMessage', label: 'HEAD Commit Message', type: 'string', required: true },
        { key: 'protected', label: 'Is Protected', type: 'boolean', required: true },
      ],
    },
    // ── Files ──
    {
      id: 'create_file',
      name: 'Create File',
      description: 'Creates a new file in the repository with specified content.',
      type: 'action',
      httpMethod: 'PUT',
      endpoint: '/repos/{owner}/{repo}/contents/{path}',
      requiredScopes: ['repo'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'filePath', label: 'File Path (e.g. docs/readme.md)', type: 'string', required: true },
        { key: 'content', label: 'File Content (text or base64)', type: 'string', required: true },
        { key: 'commitMessage', label: 'Commit Message', type: 'string', required: true },
        { key: 'branch', label: 'Branch', type: 'string', required: false, hasDynamicChoices: true, choicesFieldId: 'branchName', description: 'Default: repository default branch' },
      ],
      outputs: [
        { key: 'sha', label: 'File SHA', type: 'string', required: true },
        { key: 'htmlUrl', label: 'File URL', type: 'string', required: true },
        { key: 'commitSha', label: 'Commit SHA', type: 'string', required: true },
      ],
    },
    {
      id: 'update_file',
      name: 'Update File',
      description: 'Updates an existing file in the repository. Requires the current file SHA.',
      type: 'action',
      httpMethod: 'PUT',
      endpoint: '/repos/{owner}/{repo}/contents/{path}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'filePath', label: 'File Path', type: 'string', required: true },
        { key: 'content', label: 'New File Content', type: 'string', required: true },
        { key: 'sha', label: 'Current File SHA (required for update)', type: 'string', required: true },
        { key: 'commitMessage', label: 'Commit Message', type: 'string', required: true },
        { key: 'branch', label: 'Branch', type: 'string', required: false, hasDynamicChoices: true, choicesFieldId: 'branchName' },
      ],
      outputs: [
        { key: 'sha', label: 'New File SHA', type: 'string', required: true },
        { key: 'commitSha', label: 'Commit SHA', type: 'string', required: true },
        { key: 'htmlUrl', label: 'File URL', type: 'string', required: true },
      ],
    },
    {
      id: 'delete_file',
      name: 'Delete File',
      description: 'Deletes a file from the repository.',
      type: 'action',
      httpMethod: 'DELETE',
      endpoint: '/repos/{owner}/{repo}/contents/{path}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'filePath', label: 'File Path', type: 'string', required: true },
        { key: 'sha', label: 'File SHA (required)', type: 'string', required: true },
        { key: 'commitMessage', label: 'Commit Message', type: 'string', required: true },
        { key: 'branch', label: 'Branch', type: 'string', required: false },
      ],
      outputs: [{ key: 'commitSha', label: 'Commit SHA', type: 'string', required: true }],
    },
    {
      id: 'get_file_content',
      name: 'Get File Content',
      description: 'Fetches the content of a specific file from the repository.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/contents/{path}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'filePath', label: 'File Path', type: 'string', required: true },
        { key: 'branch', label: 'Branch (optional)', type: 'string', required: false },
      ],
      outputs: [
        { key: 'content', label: 'File Content (decoded text)', type: 'string', required: true },
        { key: 'sha', label: 'File SHA', type: 'string', required: true },
        { key: 'size', label: 'File Size (bytes)', type: 'number', required: true },
        { key: 'htmlUrl', label: 'File URL', type: 'string', required: true },
        { key: 'downloadUrl', label: 'Raw Download URL', type: 'string', required: true },
      ],
    },
    {
      id: 'list_files',
      name: 'List Files in Directory',
      description: 'Lists all files and subdirectories at a given path in the repository.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/contents/{path}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'dirPath', label: 'Directory Path (e.g. src/ or empty for root)', type: 'string', required: false },
        { key: 'branch', label: 'Branch (optional)', type: 'string', required: false },
      ],
      outputs: [
        { key: 'files', label: 'Files Array', type: 'array', required: true },
        { key: 'count', label: 'File Count', type: 'number', required: true },
      ],
    },
    // ── Commits ──
    {
      id: 'get_commit',
      name: 'Get Commit',
      description: 'Fetches details of a specific commit by SHA.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/commits/{commit_sha}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'commitSha', label: 'Commit SHA', type: 'string', required: true },
      ],
      outputs: [
        { key: 'sha', label: 'SHA', type: 'string', required: true },
        { key: 'message', label: 'Commit Message', type: 'string', required: true },
        { key: 'authorName', label: 'Author Name', type: 'string', required: true },
        { key: 'authorEmail', label: 'Author Email', type: 'string', required: true },
        { key: 'htmlUrl', label: 'Commit URL', type: 'string', required: true },
        { key: 'filesChanged', label: 'Files Changed (array)', type: 'array', required: true },
        { key: 'additions', label: 'Lines Added', type: 'number', required: true },
        { key: 'deletions', label: 'Lines Deleted', type: 'number', required: true },
      ],
    },
    {
      id: 'list_commits',
      name: 'List Commits',
      description: 'Lists commits on a branch, optionally filtered by author or path.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/commits',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'branch', label: 'Branch (optional)', type: 'string', required: false },
        { key: 'author', label: 'Author Filter (username or email)', type: 'string', required: false },
        { key: 'path', label: 'File Path Filter', type: 'string', required: false },
        { key: 'perPage', label: 'Results Per Page (max 100)', type: 'number', required: false },
      ],
      outputs: [
        { key: 'commits', label: 'Commits Array', type: 'array', required: true },
        { key: 'count', label: 'Count Returned', type: 'number', required: true },
      ],
    },
    // ── Pull Requests ──
    {
      id: 'create_pr',
      name: 'Create Pull Request',
      description: 'Creates a new pull request.',
      type: 'action',
      httpMethod: 'POST',
      endpoint: '/repos/{owner}/{repo}/pulls',
      requiredScopes: ['repo'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'title', label: 'PR Title', type: 'string', required: true },
        { key: 'body', label: 'PR Description', type: 'string', required: false },
        { key: 'headBranch', label: 'Source Branch (head)', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'branchName' },
        { key: 'baseBranch', label: 'Target Branch (base)', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'branchName' },
        { key: 'draft', label: 'Create as Draft', type: 'boolean', required: false },
      ],
      outputs: [
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
        { key: 'htmlUrl', label: 'PR URL', type: 'string', required: true },
        { key: 'state', label: 'State', type: 'string', required: true },
      ],
    },
    {
      id: 'update_pr',
      name: 'Update Pull Request',
      description: 'Updates the title, body, or state of an existing pull request.',
      type: 'action',
      httpMethod: 'PATCH',
      endpoint: '/repos/{owner}/{repo}/pulls/{pull_number}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
        { key: 'title', label: 'New Title', type: 'string', required: false },
        { key: 'body', label: 'New Body', type: 'string', required: false },
        { key: 'state', label: 'State', type: 'select', required: false, options: [{ label: 'Open', value: 'open' }, { label: 'Closed', value: 'closed' }] },
      ],
      outputs: [
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
        { key: 'state', label: 'State', type: 'string', required: true },
        { key: 'updatedAt', label: 'Updated At', type: 'string', required: true },
      ],
    },
    {
      id: 'merge_pr',
      name: 'Merge Pull Request',
      description: 'Merges an open pull request.',
      type: 'action',
      httpMethod: 'PUT',
      endpoint: '/repos/{owner}/{repo}/pulls/{pull_number}/merge',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
        { key: 'mergeMethod', label: 'Merge Method', type: 'select', required: false, options: [{ label: 'Merge Commit', value: 'merge' }, { label: 'Squash', value: 'squash' }, { label: 'Rebase', value: 'rebase' }] },
        { key: 'commitTitle', label: 'Commit Title (optional)', type: 'string', required: false },
        { key: 'commitMessage', label: 'Commit Message (optional)', type: 'string', required: false },
      ],
      outputs: [
        { key: 'merged', label: 'Was Merged', type: 'boolean', required: true },
        { key: 'sha', label: 'Merge Commit SHA', type: 'string', required: true },
        { key: 'message', label: 'Response Message', type: 'string', required: true },
      ],
    },
    {
      id: 'close_pr',
      name: 'Close Pull Request',
      description: 'Closes an open pull request without merging.',
      type: 'action',
      httpMethod: 'PATCH',
      endpoint: '/repos/{owner}/{repo}/pulls/{pull_number}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
      ],
      outputs: [{ key: 'state', label: 'New State', type: 'string', required: true }],
    },
    {
      id: 'list_prs',
      name: 'List Pull Requests',
      description: 'Lists pull requests in a repository with optional filters.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/pulls',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'state', label: 'State Filter', type: 'select', required: false, options: [{ label: 'Open', value: 'open' }, { label: 'Closed', value: 'closed' }, { label: 'All', value: 'all' }] },
        { key: 'base', label: 'Base Branch Filter', type: 'string', required: false },
        { key: 'perPage', label: 'Per Page (max 100)', type: 'number', required: false },
      ],
      outputs: [
        { key: 'prs', label: 'Pull Requests Array', type: 'array', required: true },
        { key: 'count', label: 'Count', type: 'number', required: true },
      ],
    },
    {
      id: 'get_pr',
      name: 'Get Pull Request',
      description: 'Fetches details of a specific pull request by number.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/pulls/{pull_number}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
      ],
      outputs: [
        { key: 'prNumber', label: 'PR Number', type: 'number', required: true },
        { key: 'title', label: 'Title', type: 'string', required: true },
        { key: 'state', label: 'State', type: 'string', required: true },
        { key: 'merged', label: 'Is Merged', type: 'boolean', required: true },
        { key: 'authorLogin', label: 'Author', type: 'string', required: true },
        { key: 'reviewers', label: 'Reviewers (array)', type: 'array', required: false },
        { key: 'commitsCount', label: 'Commits Count', type: 'number', required: true },
        { key: 'additions', label: 'Lines Added', type: 'number', required: true },
        { key: 'deletions', label: 'Lines Deleted', type: 'number', required: true },
        { key: 'htmlUrl', label: 'PR URL', type: 'string', required: true },
      ],
    },
    // ── Issues ──
    {
      id: 'create_issue',
      name: 'Create Issue',
      description: 'Creates a new issue in a repository.',
      type: 'action',
      httpMethod: 'POST',
      endpoint: '/repos/{owner}/{repo}/issues',
      requiredScopes: ['repo'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'title', label: 'Issue Title', type: 'string', required: true },
        { key: 'body', label: 'Issue Body', type: 'string', required: false },
        { key: 'labels', label: 'Labels (comma-separated)', type: 'string', required: false },
        { key: 'assignees', label: 'Assignees (comma-separated usernames)', type: 'string', required: false },
        { key: 'milestone', label: 'Milestone Number', type: 'number', required: false },
      ],
      outputs: [
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'htmlUrl', label: 'Issue URL', type: 'string', required: true },
        { key: 'state', label: 'State', type: 'string', required: true },
        { key: 'nodeId', label: 'Node ID', type: 'string', required: true },
      ],
    },
    {
      id: 'update_issue',
      name: 'Update Issue',
      description: 'Updates the title, body, labels, assignees, or state of an issue.',
      type: 'action',
      httpMethod: 'PATCH',
      endpoint: '/repos/{owner}/{repo}/issues/{issue_number}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'title', label: 'New Title', type: 'string', required: false },
        { key: 'body', label: 'New Body', type: 'string', required: false },
        { key: 'state', label: 'State', type: 'select', required: false, options: [{ label: 'Open', value: 'open' }, { label: 'Closed', value: 'closed' }] },
        { key: 'labels', label: 'Labels (comma-separated)', type: 'string', required: false },
        { key: 'assignees', label: 'Assignees (comma-separated)', type: 'string', required: false },
      ],
      outputs: [
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'state', label: 'State', type: 'string', required: true },
        { key: 'updatedAt', label: 'Updated At', type: 'string', required: true },
        { key: 'htmlUrl', label: 'Issue URL', type: 'string', required: true },
      ],
    },
    {
      id: 'close_issue',
      name: 'Close Issue',
      description: 'Closes an open issue.',
      type: 'action',
      httpMethod: 'PATCH',
      endpoint: '/repos/{owner}/{repo}/issues/{issue_number}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'stateReason', label: 'Close Reason', type: 'select', required: false, options: [{ label: 'Completed', value: 'completed' }, { label: 'Not Planned', value: 'not_planned' }] },
      ],
      outputs: [
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'state', label: 'State', type: 'string', required: true },
        { key: 'closedAt', label: 'Closed At', type: 'string', required: true },
      ],
    },
    {
      id: 'list_issues',
      name: 'List Issues',
      description: 'Lists issues in a repository with optional filters.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/issues',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'state', label: 'State Filter', type: 'select', required: false, options: [{ label: 'Open', value: 'open' }, { label: 'Closed', value: 'closed' }, { label: 'All', value: 'all' }] },
        { key: 'labels', label: 'Label Filter (comma-separated)', type: 'string', required: false },
        { key: 'assignee', label: 'Assignee Filter', type: 'string', required: false },
        { key: 'since', label: 'Since Date (ISO 8601)', type: 'string', required: false },
        { key: 'perPage', label: 'Per Page (max 100)', type: 'number', required: false },
      ],
      outputs: [
        { key: 'issues', label: 'Issues Array', type: 'array', required: true },
        { key: 'count', label: 'Count', type: 'number', required: true },
      ],
    },
    {
      id: 'get_issue',
      name: 'Get Issue',
      description: 'Fetches details of a specific issue by number.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/issues/{issue_number}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
      ],
      outputs: [
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'title', label: 'Title', type: 'string', required: true },
        { key: 'body', label: 'Body', type: 'string', required: false },
        { key: 'state', label: 'State', type: 'string', required: true },
        { key: 'authorLogin', label: 'Author', type: 'string', required: true },
        { key: 'labels', label: 'Labels', type: 'array', required: false },
        { key: 'assignees', label: 'Assignees', type: 'array', required: false },
        { key: 'htmlUrl', label: 'Issue URL', type: 'string', required: true },
        { key: 'commentsCount', label: 'Comments Count', type: 'number', required: true },
        { key: 'createdAt', label: 'Created At', type: 'string', required: true },
        { key: 'updatedAt', label: 'Updated At', type: 'string', required: true },
      ],
    },
    {
      id: 'create_issue_comment',
      name: 'Create Issue Comment',
      description: 'Adds a new comment to an existing issue.',
      type: 'action',
      httpMethod: 'POST',
      endpoint: '/repos/{owner}/{repo}/issues/{issue_number}/comments',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'body', label: 'Comment Text', type: 'string', required: true },
      ],
      outputs: [
        { key: 'commentId', label: 'Comment ID', type: 'number', required: true },
        { key: 'htmlUrl', label: 'Comment URL', type: 'string', required: true },
        { key: 'createdAt', label: 'Created At', type: 'string', required: true },
      ],
    },
    {
      id: 'list_issue_comments',
      name: 'List Issue Comments',
      description: 'Fetches all comments on a specific issue.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/issues/{issue_number}/comments',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'issueNumber', label: 'Issue Number', type: 'number', required: true },
        { key: 'perPage', label: 'Per Page (max 100)', type: 'number', required: false },
      ],
      outputs: [
        { key: 'comments', label: 'Comments Array', type: 'array', required: true },
        { key: 'count', label: 'Count', type: 'number', required: true },
      ],
    },
    // ── Releases ──
    {
      id: 'create_release',
      name: 'Create Release',
      description: 'Creates a new release for a tag in the repository.',
      type: 'action',
      httpMethod: 'POST',
      endpoint: '/repos/{owner}/{repo}/releases',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'tagName', label: 'Tag Name (e.g. v1.2.0)', type: 'string', required: true },
        { key: 'releaseName', label: 'Release Name', type: 'string', required: false },
        { key: 'body', label: 'Release Notes', type: 'string', required: false },
        { key: 'draft', label: 'Create as Draft', type: 'boolean', required: false },
        { key: 'prerelease', label: 'Mark as Pre-release', type: 'boolean', required: false },
        { key: 'targetCommitish', label: 'Target Branch or SHA', type: 'string', required: false },
        { key: 'generateReleaseNotes', label: 'Auto-generate Release Notes', type: 'boolean', required: false },
      ],
      outputs: [
        { key: 'releaseId', label: 'Release ID', type: 'number', required: true },
        { key: 'htmlUrl', label: 'Release URL', type: 'string', required: true },
        { key: 'tagName', label: 'Tag Name', type: 'string', required: true },
        { key: 'uploadUrl', label: 'Asset Upload URL', type: 'string', required: true },
        { key: 'publishedAt', label: 'Published At', type: 'string', required: false },
      ],
    },
    {
      id: 'list_releases',
      name: 'List Releases',
      description: 'Lists all releases in the repository.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/releases',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'perPage', label: 'Per Page (max 100)', type: 'number', required: false },
      ],
      outputs: [
        { key: 'releases', label: 'Releases Array', type: 'array', required: true },
        { key: 'count', label: 'Count', type: 'number', required: true },
      ],
    },
    // ── GitHub Actions / Workflows ──
    {
      id: 'trigger_workflow',
      name: 'Trigger GitHub Actions Workflow',
      description: 'Manually triggers a workflow_dispatch event to run a workflow.',
      type: 'action',
      httpMethod: 'POST',
      endpoint: '/repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches',
      requiredScopes: ['workflow'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'workflowId', label: 'Workflow File Name or ID (e.g. deploy.yml)', type: 'string', required: true },
        { key: 'ref', label: 'Branch or Tag to Run On', type: 'string', required: true },
        { key: 'inputs', label: 'Workflow Inputs (JSON object)', type: 'json', required: false },
      ],
      outputs: [
        { key: 'triggered', label: 'Was Triggered', type: 'boolean', required: true },
        { key: 'message', label: 'Response Message', type: 'string', required: true },
      ],
    },
    {
      id: 'get_workflow_run',
      name: 'Get Workflow Run Status',
      description: 'Fetches the status and details of a specific workflow run.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/actions/runs/{run_id}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'runId', label: 'Run ID', type: 'number', required: true },
      ],
      outputs: [
        { key: 'runId', label: 'Run ID', type: 'number', required: true },
        { key: 'status', label: 'Status (queued/in_progress/completed)', type: 'string', required: true },
        { key: 'conclusion', label: 'Conclusion (success/failure/cancelled)', type: 'string', required: false },
        { key: 'workflowName', label: 'Workflow Name', type: 'string', required: true },
        { key: 'htmlUrl', label: 'Run URL', type: 'string', required: true },
        { key: 'createdAt', label: 'Started At', type: 'string', required: true },
        { key: 'updatedAt', label: 'Updated At', type: 'string', required: true },
      ],
    },
    {
      id: 'list_workflow_runs',
      name: 'List Workflow Runs',
      description: 'Lists workflow runs for a specific workflow or all workflows in the repository.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/actions/runs',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'workflowId', label: 'Workflow File Name (optional)', type: 'string', required: false },
        { key: 'status', label: 'Status Filter', type: 'select', required: false, options: [{ label: 'Completed', value: 'completed' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Queued', value: 'queued' }, { label: 'Failed', value: 'failure' }] },
        { key: 'branch', label: 'Branch Filter', type: 'string', required: false },
        { key: 'perPage', label: 'Per Page (max 100)', type: 'number', required: false },
      ],
      outputs: [
        { key: 'runs', label: 'Workflow Runs Array', type: 'array', required: true },
        { key: 'totalCount', label: 'Total Count', type: 'number', required: true },
      ],
    },
    // ── Collaborators ──
    {
      id: 'add_collaborator',
      name: 'Add Collaborator',
      description: 'Invites a user as a collaborator to the repository.',
      type: 'action',
      httpMethod: 'PUT',
      endpoint: '/repos/{owner}/{repo}/collaborators/{username}',
      requiredScopes: ['repo'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'username', label: 'GitHub Username to Invite', type: 'string', required: true },
        { key: 'permission', label: 'Permission Level', type: 'select', required: false, options: [{ label: 'Read', value: 'pull' }, { label: 'Triage', value: 'triage' }, { label: 'Write', value: 'push' }, { label: 'Maintain', value: 'maintain' }, { label: 'Admin', value: 'admin' }] },
      ],
      outputs: [
        { key: 'invited', label: 'Was Invited', type: 'boolean', required: true },
        { key: 'invitationId', label: 'Invitation ID', type: 'number', required: false },
        { key: 'permission', label: 'Permission Granted', type: 'string', required: true },
      ],
    },
    {
      id: 'remove_collaborator',
      name: 'Remove Collaborator',
      description: 'Removes a collaborator from the repository.',
      type: 'action',
      httpMethod: 'DELETE',
      endpoint: '/repos/{owner}/{repo}/collaborators/{username}',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'username', label: 'GitHub Username to Remove', type: 'string', required: true },
      ],
      outputs: [{ key: 'removed', label: 'Was Removed', type: 'boolean', required: true }],
    },
    {
      id: 'list_collaborators',
      name: 'List Collaborators',
      description: 'Lists all collaborators of the repository.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/collaborators',
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'permission', label: 'Permission Filter', type: 'select', required: false, options: [{ label: 'All', value: 'all' }, { label: 'Pull', value: 'pull' }, { label: 'Push', value: 'push' }, { label: 'Admin', value: 'admin' }] },
      ],
      outputs: [
        { key: 'collaborators', label: 'Collaborators Array', type: 'array', required: true },
        { key: 'count', label: 'Count', type: 'number', required: true },
      ],
    },
    // ── Stats ──
    {
      id: 'get_traffic_stats',
      name: 'Get Repository Traffic Stats',
      description: 'Fetches view counts, clone counts, and popular content for the repository.',
      type: 'action',
      httpMethod: 'GET',
      endpoint: '/repos/{owner}/{repo}/traffic/views',
      requiredScopes: ['repo'],
      inputs: [
        { key: 'repoName', label: 'Repository', type: 'string', required: true, hasDynamicChoices: true, choicesFieldId: 'repoName' },
        { key: 'per', label: 'Breakdown Period', type: 'select', required: false, options: [{ label: 'Day', value: 'day' }, { label: 'Week', value: 'week' }] },
      ],
      outputs: [
        { key: 'totalViews', label: 'Total Views', type: 'number', required: true },
        { key: 'uniqueViews', label: 'Unique Visitors', type: 'number', required: true },
        { key: 'totalClones', label: 'Total Clones', type: 'number', required: false },
        { key: 'uniqueClones', label: 'Unique Cloners', type: 'number', required: false },
        { key: 'views', label: 'Daily/Weekly Views Breakdown', type: 'array', required: true },
      ],
      rateLimitInfo: { notes: 'Only available for repositories you own or have admin access to.' },
    },
  ],
};
