import { ConnectorManifest } from '@automation/shared-types';

export const ALL_50_CONNECTOR_MANIFESTS: ConnectorManifest[] = [
  // Google Suite
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Read emails, search inbox, send notifications, reply to threads & create drafts.',
    category: 'Google Suite',
    icon: '/icons/gmail.svg',
    authType: 'oauth2',
    triggers: [{ id: 'new_email', name: 'New Email Received', description: 'Triggers on new inbox email.', type: 'trigger', inputs: [], outputs: [{ key: 'subject', label: 'Subject', type: 'string', required: true }] }],
    actions: [{ id: 'send_email', name: 'Send Email Message', description: 'Sends email notification.', type: 'action', inputs: [{ key: 'to', label: 'Recipient Email', type: 'string', required: true }], outputs: [{ key: 'status', label: 'Status', type: 'string', required: true }] }],
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    description: 'Append rows, create spreadsheets, auto-create worksheet tabs & read cell ranges.',
    category: 'Google Suite',
    icon: '/icons/sheets.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'append_row', name: 'Append Row to Worksheet', description: 'Appends data row.', type: 'action', inputs: [{ key: 'spreadsheetId', label: 'Spreadsheet ID', type: 'string', required: true }], outputs: [{ key: 'updatedRange', label: 'Updated Range', type: 'string', required: true }] }],
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Upload files, create folders, share links & search Drive storage.',
    category: 'Google Suite',
    icon: '/icons/drive.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'upload_file', name: 'Upload File', description: 'Uploads file payload.', type: 'action', inputs: [{ key: 'fileName', label: 'File Name', type: 'string', required: true }], outputs: [{ key: 'fileUrl', label: 'File URL', type: 'string', required: true }] }],
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Schedule meetings, create events, set reminders & list calendars.',
    category: 'Google Suite',
    icon: '/icons/calendar.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'create_event', name: 'Create Calendar Event', description: 'Schedules new event.', type: 'action', inputs: [{ key: 'title', label: 'Event Title', type: 'string', required: true }], outputs: [{ key: 'eventLink', label: 'Event Link', type: 'string', required: true }] }],
  },
  {
    id: 'google-docs',
    name: 'Google Docs',
    description: 'Create documents, read content, format text & append paragraphs.',
    category: 'Google Suite',
    icon: '/icons/docs.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'create_doc', name: 'Create Document', description: 'Creates new Google Doc.', type: 'action', inputs: [{ key: 'title', label: 'Document Title', type: 'string', required: true }], outputs: [{ key: 'documentId', label: 'Document ID', type: 'string', required: true }] }],
  },

  // Communication & Messaging
  {
    id: 'outlook',
    name: 'Microsoft Outlook',
    description: 'Read Outlook emails, send email messages, manage mail folders & attachments.',
    category: 'Communication',
    icon: '/icons/outlook.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'send_email', name: 'Send Outlook Email', description: 'Sends transactional email.', type: 'action', inputs: [{ key: 'to', label: 'Recipient', type: 'string', required: true }], outputs: [{ key: 'status', label: 'Status', type: 'string', required: true }] }],
  },
  {
    id: 'ms-teams',
    name: 'Microsoft Teams',
    description: 'Post channel announcements, send adaptive cards & chat messages.',
    category: 'Communication',
    icon: '/icons/teams.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'post_channel', name: 'Post Channel Message', description: 'Posts message to channel.', type: 'action', inputs: [{ key: 'message', label: 'Message Text', type: 'string', required: true }], outputs: [{ key: 'status', label: 'Status', type: 'string', required: true }] }],
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Post messages, upload snippets, trigger slash commands & listen for events.',
    category: 'Communication',
    icon: '/icons/slack.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'send_message', name: 'Post Channel Message', description: 'Posts message to Slack channel.', type: 'action', inputs: [{ key: 'channel', label: 'Channel Name', type: 'string', required: true }], outputs: [{ key: 'ts', label: 'Message Timestamp', type: 'string', required: true }] }],
  },
  {
    id: 'discord',
    name: 'Discord Bot',
    description: 'Send channel embeds, dispatch webhooks & trigger Discord bot notifications.',
    category: 'Communication',
    icon: '/icons/discord.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'post_embed', name: 'Post Discord Embed', description: 'Posts rich embed card.', type: 'action', inputs: [{ key: 'content', label: 'Content', type: 'string', required: true }], outputs: [{ key: 'status', label: 'Status', type: 'string', required: true }] }],
  },
  {
    id: 'telegram',
    name: 'Telegram Bot',
    description: 'Send bot messages, broadcast channel alerts & handle command callbacks.',
    category: 'Communication',
    icon: '/icons/telegram.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'send_message', name: 'Send Telegram Message', description: 'Sends bot message.', type: 'action', inputs: [{ key: 'chatId', label: 'Chat ID', type: 'string', required: true }], outputs: [{ key: 'messageId', label: 'Message ID', type: 'number', required: true }] }],
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Business',
    description: 'Send template messages, receive customer replies & dispatch notifications.',
    category: 'Communication',
    icon: '/icons/whatsapp.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'send_message', name: 'Send WhatsApp Message', description: 'Sends WhatsApp message.', type: 'action', inputs: [{ key: 'phone', label: 'Phone Number', type: 'string', required: true }], outputs: [{ key: 'status', label: 'Status', type: 'string', required: true }] }],
  },
  {
    id: 'twilio',
    name: 'Twilio SMS',
    description: 'Send SMS text messages, dispatch WhatsApp templates & initiate voice calls.',
    category: 'Communication',
    icon: '/icons/twilio.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'send_sms', name: 'Send SMS Message', description: 'Sends SMS notification.', type: 'action', inputs: [{ key: 'to', label: 'Phone Number', type: 'string', required: true }], outputs: [{ key: 'sid', label: 'SMS SID', type: 'string', required: true }] }],
  },
  {
    id: 'zoom',
    name: 'Zoom Meetings',
    description: 'Schedule video meetings, create webinars & manage meeting registrants.',
    category: 'Communication',
    icon: '/icons/zoom.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'create_meeting', name: 'Create Zoom Meeting', description: 'Schedules instant meeting.', type: 'action', inputs: [{ key: 'topic', label: 'Meeting Topic', type: 'string', required: true }], outputs: [{ key: 'joinUrl', label: 'Join URL', type: 'string', required: true }] }],
  },

  // AI Suite
  {
    id: 'openai',
    name: 'OpenAI GPT-4o',
    description: 'ChatGPT, GPT-4o vision, custom system prompts, JSON structured outputs & tools.',
    category: 'AI Native',
    icon: '/icons/openai.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'chat_completion', name: 'GPT-4o Completion', description: 'Generates AI completion.', type: 'action', inputs: [{ key: 'prompt', label: 'Prompt', type: 'string', required: true }], outputs: [{ key: 'result', label: 'AI Output', type: 'string', required: true }] }],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude 3.5',
    description: 'Claude 3.5 Sonnet, long context analysis, code reasoning & structured extraction.',
    category: 'AI Native',
    icon: '/icons/claude.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'claude_prompt', name: 'Claude 3.5 Prompt', description: 'Generates Claude response.', type: 'action', inputs: [{ key: 'prompt', label: 'Prompt', type: 'string', required: true }], outputs: [{ key: 'result', label: 'AI Output', type: 'string', required: true }] }],
  },
  {
    id: 'gemini',
    name: 'Google Gemini 2.0',
    description: 'Gemini 2.0 Flash, multimodal processing, fast reasoning & document understanding.',
    category: 'AI Native',
    icon: '/icons/gemini.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'gemini_flash', name: 'Gemini 2.0 Execution', description: 'Runs Gemini Flash completion.', type: 'action', inputs: [{ key: 'prompt', label: 'Prompt', type: 'string', required: true }], outputs: [{ key: 'result', label: 'AI Output', type: 'string', required: true }] }],
  },
  {
    id: 'groq',
    name: 'Groq Llama 3',
    description: 'Sub-second ultrafast Llama 3 70B inference engine for real-time workflows.',
    category: 'AI Native',
    icon: '/icons/groq.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'fast_chat', name: 'Groq Ultrafast Chat', description: 'Sub-second AI response.', type: 'action', inputs: [{ key: 'prompt', label: 'Prompt', type: 'string', required: true }], outputs: [{ key: 'result', label: 'AI Output', type: 'string', required: true }] }],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs Voice AI',
    description: 'AI Text-to-Speech audio synthesis, voice cloning & speech-to-text transcriptions.',
    category: 'AI Native',
    icon: '/icons/elevenlabs.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'text_to_speech', name: 'Text-to-Speech Audio', description: 'Synthesizes AI audio.', type: 'action', inputs: [{ key: 'text', label: 'Text Payload', type: 'string', required: true }], outputs: [{ key: 'audioUrl', label: 'Audio File URL', type: 'string', required: true }] }],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Inference',
    description: 'Run open-source Machine Learning models, image generation & NLP pipelines.',
    category: 'AI Native',
    icon: '/icons/huggingface.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'model_predict', name: 'Run Model Inference', description: 'Executes ML model.', type: 'action', inputs: [{ key: 'modelId', label: 'Model ID', type: 'string', required: true }], outputs: [{ key: 'output', label: 'Model Output', type: 'json', required: true }] }],
  },

  // Databases & Infrastructure
  {
    id: 'postgresql',
    name: 'PostgreSQL Database',
    description: 'Execute SQL queries, insert rows, update records & stream database triggers.',
    category: 'Databases',
    icon: '/icons/postgres.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'sql_query', name: 'Execute SQL Query', description: 'Executes Postgres SQL.', type: 'action', inputs: [{ key: 'query', label: 'SQL Query', type: 'string', required: true }], outputs: [{ key: 'rows', label: 'Result Rows', type: 'json', required: true }] }],
  },
  {
    id: 'mysql',
    name: 'MySQL Database',
    description: 'Run MySQL queries, query tables & insert structured database records.',
    category: 'Databases',
    icon: '/icons/mysql.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'sql_query', name: 'Execute MySQL Query', description: 'Runs MySQL statement.', type: 'action', inputs: [{ key: 'query', label: 'SQL Statement', type: 'string', required: true }], outputs: [{ key: 'results', label: 'Query Results', type: 'json', required: true }] }],
  },
  {
    id: 'mongodb',
    name: 'MongoDB Atlas',
    description: 'Insert JSON documents, query collections, run aggregations & document triggers.',
    category: 'Databases',
    icon: '/icons/mongodb.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'insert_document', name: 'Insert Mongo Document', description: 'Inserts document.', type: 'action', inputs: [{ key: 'collection', label: 'Collection Name', type: 'string', required: true }], outputs: [{ key: 'insertedId', label: 'Inserted ID', type: 'string', required: true }] }],
  },
  {
    id: 'redis',
    name: 'Redis Cache & Store',
    description: 'Get/Set key-value pairs, handle pub/sub channels & rate-limit counters.',
    category: 'Databases',
    icon: '/icons/redis.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'cache_get_set', name: 'Redis Set Key', description: 'Sets Redis cache key.', type: 'action', inputs: [{ key: 'key', label: 'Key', type: 'string', required: true }], outputs: [{ key: 'val', label: 'Stored Value', type: 'string', required: true }] }],
  },
  {
    id: 'supabase',
    name: 'Supabase Database',
    description: 'Query Postgres tables, handle Supabase Auth & trigger storage bucket events.',
    category: 'Databases',
    icon: '/icons/supabase.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'query_table', name: 'Query Supabase Table', description: 'Queries table records.', type: 'action', inputs: [{ key: 'table', label: 'Table Name', type: 'string', required: true }], outputs: [{ key: 'data', label: 'Table Data', type: 'json', required: true }] }],
  },
  {
    id: 'firebase',
    name: 'Firebase Firestore',
    description: 'Read & write Firestore documents, handle Auth triggers & Cloud Messaging.',
    category: 'Databases',
    icon: '/icons/firebase.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'store_doc', name: 'Add Firestore Document', description: 'Stores document in Firestore.', type: 'action', inputs: [{ key: 'collectionPath', label: 'Collection Path', type: 'string', required: true }], outputs: [{ key: 'docId', label: 'Document ID', type: 'string', required: true }] }],
  },
  {
    id: 'aws-s3',
    name: 'AWS S3 Storage',
    description: 'Upload S3 file objects, generate presigned URLs & manage S3 bucket files.',
    category: 'Databases',
    icon: '/icons/aws-s3.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'put_object', name: 'Upload Object to S3', description: 'Uploads file to S3 bucket.', type: 'action', inputs: [{ key: 'bucket', label: 'Bucket Name', type: 'string', required: true }], outputs: [{ key: 'location', label: 'S3 Object URL', type: 'string', required: true }] }],
  },
  {
    id: 'bigquery',
    name: 'Google BigQuery',
    description: 'Run SQL analytics queries, append BigQuery rows & export dataset reports.',
    category: 'Databases',
    icon: '/icons/bigquery.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'run_query', name: 'Run BigQuery SQL', description: 'Executes analytics query.', type: 'action', inputs: [{ key: 'query', label: 'BigQuery SQL', type: 'string', required: true }], outputs: [{ key: 'totalRows', label: 'Total Rows', type: 'number', required: true }] }],
  },

  // CRM & Sales
  {
    id: 'hubspot',
    name: 'HubSpot CRM',
    description: 'Create contacts, update deal pipeline stages, list companies & log activities.',
    category: 'CRM & Sales',
    icon: '/icons/hubspot.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'create_contact', name: 'Create HubSpot Contact', description: 'Creates CRM contact.', type: 'action', inputs: [{ key: 'email', label: 'Email', type: 'string', required: true }], outputs: [{ key: 'contactId', label: 'Contact ID', type: 'string', required: true }] }],
  },
  {
    id: 'salesforce',
    name: 'Salesforce CRM',
    description: 'Manage leads, opportunities, accounts & custom Salesforce SOQL queries.',
    category: 'CRM & Sales',
    icon: '/icons/salesforce.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'create_lead', name: 'Create Salesforce Lead', description: 'Creates sales lead.', type: 'action', inputs: [{ key: 'lastName', label: 'Last Name', type: 'string', required: true }], outputs: [{ key: 'leadId', label: 'Lead ID', type: 'string', required: true }] }],
  },

  // Payments & E-Commerce
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payment events, create checkout links, manage subscriptions & charge cards.',
    category: 'Finance',
    icon: '/icons/stripe.svg',
    authType: 'api_key',
    triggers: [{ id: 'payment_intent_succeeded', name: 'Payment Succeeded', description: 'Triggers on charge.', type: 'trigger', inputs: [], outputs: [{ key: 'amount', label: 'Amount Paid', type: 'number', required: true }] }],
    actions: [{ id: 'create_customer', name: 'Create Stripe Customer', description: 'Creates payment customer.', type: 'action', inputs: [{ key: 'email', label: 'Email', type: 'string', required: true }], outputs: [{ key: 'customerId', label: 'Customer ID', type: 'string', required: true }] }],
  },
  {
    id: 'razorpay',
    name: 'Razorpay (India)',
    description: 'Create UPI & card payment links, handle payment captures & Indian refunds.',
    category: 'Finance',
    icon: '/icons/razorpay.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'create_payment_link', name: 'Create Razorpay Link', description: 'Creates UPI checkout link.', type: 'action', inputs: [{ key: 'amount', label: 'Amount (INR)', type: 'number', required: true }], outputs: [{ key: 'shortUrl', label: 'Payment Link URL', type: 'string', required: true }] }],
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Fulfill customer orders, sync product inventory & trigger on paid checkouts.',
    category: 'E-Commerce',
    icon: '/icons/shopify.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'get_order', name: 'Get Order Details', description: 'Fetches order data.', type: 'action', inputs: [{ key: 'orderId', label: 'Order ID', type: 'string', required: true }], outputs: [{ key: 'totalPrice', label: 'Total Price', type: 'string', required: true }] }],
  },
  {
    id: 'amazon-flipkart',
    name: 'Amazon & Flipkart',
    description: 'Track price drops, compare product deals, monitor stock & manage orders.',
    category: 'E-Commerce',
    icon: '/icons/shopping.svg',
    authType: 'none',
    triggers: [],
    actions: [{ id: 'search_products', name: 'Search Product Deals', description: 'Searches live listings.', type: 'action', inputs: [{ key: 'keyword', label: 'Keyword Search', type: 'string', required: true }], outputs: [{ key: 'summary', label: 'Deals Digest', type: 'string', required: true }] }],
  },

  // Code Repositories & DevOps
  {
    id: 'github',
    name: 'GitHub',
    description: 'Create issues, post pull request comments, trigger workflows & listen for commits.',
    category: 'Developer Tools',
    icon: '/icons/github.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'create_issue', name: 'Create GitHub Issue', description: 'Creates repository issue.', type: 'action', inputs: [{ key: 'repo', label: 'Repository', type: 'string', required: true }], outputs: [{ key: 'issueUrl', label: 'Issue URL', type: 'string', required: true }] }],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'Trigger CI/CD pipelines, manage repository issues & merge requests.',
    category: 'Developer Tools',
    icon: '/icons/gitlab.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'trigger_pipeline', name: 'Trigger GitLab CI/CD Pipeline', description: 'Runs pipeline.', type: 'action', inputs: [{ key: 'projectId', label: 'Project ID', type: 'string', required: true }], outputs: [{ key: 'pipelineId', label: 'Pipeline ID', type: 'number', required: true }] }],
  },

  // Email Marketing & Transactional Email
  {
    id: 'sendgrid',
    name: 'SendGrid Email API',
    description: 'Send transactional emails, manage email templates & contact suppression lists.',
    category: 'Marketing',
    icon: '/icons/sendgrid.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'send_mail', name: 'Send SendGrid Email', description: 'Sends API email.', type: 'action', inputs: [{ key: 'to', label: 'To Email', type: 'string', required: true }], outputs: [{ key: 'status', label: 'Status', type: 'string', required: true }] }],
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    description: 'Add campaign subscribers, update contact tags & trigger email automation sequences.',
    category: 'Marketing',
    icon: '/icons/mailchimp.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'add_subscriber', name: 'Add Subscriber to List', description: 'Adds subscriber.', type: 'action', inputs: [{ key: 'email', label: 'Subscriber Email', type: 'string', required: true }], outputs: [{ key: 'id', label: 'Subscriber ID', type: 'string', required: true }] }],
  },
  {
    id: 'resend',
    name: 'Resend Email API',
    description: 'Send modern developer-friendly transactional emails with React templates.',
    category: 'Marketing',
    icon: '/icons/resend.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'send_transactional', name: 'Send Resend Email', description: 'Sends API email.', type: 'action', inputs: [{ key: 'to', label: 'To Address', type: 'string', required: true }], outputs: [{ key: 'emailId', label: 'Email ID', type: 'string', required: true }] }],
  },

  // Productivity & Project Management
  {
    id: 'notion',
    name: 'Notion DB',
    description: 'Create pages, query workspace databases & update block content.',
    category: 'Productivity',
    icon: '/icons/notion.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'create_page', name: 'Create Notion Page', description: 'Creates page in database.', type: 'action', inputs: [{ key: 'title', label: 'Page Title', type: 'string', required: true }], outputs: [{ key: 'pageId', label: 'Page ID', type: 'string', required: true }] }],
  },
  {
    id: 'airtable',
    name: 'Airtable Base',
    description: 'Add records to Airtable bases, update grid cells & search view records.',
    category: 'Productivity',
    icon: '/icons/airtable.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'add_record', name: 'Create Airtable Record', description: 'Creates row record.', type: 'action', inputs: [{ key: 'baseId', label: 'Base ID', type: 'string', required: true }], outputs: [{ key: 'recordId', label: 'Record ID', type: 'string', required: true }] }],
  },
  {
    id: 'jira',
    name: 'Jira Software',
    description: 'Create Jira issue tickets, update sprint boards & transition issue statuses.',
    category: 'Productivity',
    icon: '/icons/jira.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'create_issue', name: 'Create Jira Ticket', description: 'Creates Jira issue.', type: 'action', inputs: [{ key: 'summary', label: 'Issue Summary', type: 'string', required: true }], outputs: [{ key: 'key', label: 'Issue Key (e.g. PROJ-123)', type: 'string', required: true }] }],
  },
  {
    id: 'linear',
    name: 'Linear App',
    description: 'Create Linear issue tickets, set priorities & assign cycle deadlines.',
    category: 'Productivity',
    icon: '/icons/linear.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'create_ticket', name: 'Create Linear Issue', description: 'Creates Linear ticket.', type: 'action', inputs: [{ key: 'title', label: 'Issue Title', type: 'string', required: true }], outputs: [{ key: 'identifier', label: 'Issue Identifier', type: 'string', required: true }] }],
  },
  {
    id: 'clickup',
    name: 'ClickUp Tasks',
    description: 'Create ClickUp tasks, set assignees & update custom task fields.',
    category: 'Productivity',
    icon: '/icons/clickup.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'create_task', name: 'Create ClickUp Task', description: 'Creates task.', type: 'action', inputs: [{ key: 'name', label: 'Task Name', type: 'string', required: true }], outputs: [{ key: 'taskId', label: 'Task ID', type: 'string', required: true }] }],
  },
  {
    id: 'trello',
    name: 'Trello Boards',
    description: 'Create Trello cards, move cards across board columns & add labels.',
    category: 'Productivity',
    icon: '/icons/trello.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'create_card', name: 'Create Trello Card', description: 'Creates card on board.', type: 'action', inputs: [{ key: 'name', label: 'Card Name', type: 'string', required: true }], outputs: [{ key: 'cardId', label: 'Card ID', type: 'string', required: true }] }],
  },

  // Analytics & Forms
  {
    id: 'google-analytics',
    name: 'Google Analytics 4',
    description: 'Query GA4 metrics, track event conversions & fetch user active sessions.',
    category: 'Analytics',
    icon: '/icons/ga4.svg',
    authType: 'oauth2',
    triggers: [],
    actions: [{ id: 'get_metrics', name: 'Run GA4 Report Query', description: 'Fetches analytics metrics.', type: 'action', inputs: [{ key: 'propertyId', label: 'GA4 Property ID', type: 'string', required: true }], outputs: [{ key: 'activeUsers', label: 'Active Users', type: 'number', required: true }] }],
  },
  {
    id: 'calendly',
    name: 'Calendly',
    description: 'Trigger on new booking invitees, cancel events & list meeting schedules.',
    category: 'Productivity',
    icon: '/icons/calendly.svg',
    authType: 'oauth2',
    triggers: [{ id: 'invitee_created', name: 'New Booking Created', description: 'Triggers on new booking.', type: 'trigger', inputs: [], outputs: [{ key: 'inviteeEmail', label: 'Invitee Email', type: 'string', required: true }] }],
    actions: [],
  },
  {
    id: 'typeform',
    name: 'Typeform',
    description: 'Trigger on new form submission responses & fetch dynamic questionnaire answers.',
    category: 'Productivity',
    icon: '/icons/typeform.svg',
    authType: 'oauth2',
    triggers: [{ id: 'form_submitted', name: 'Form Submitted', description: 'Triggers on form response.', type: 'trigger', inputs: [], outputs: [{ key: 'responseId', label: 'Response ID', type: 'string', required: true }] }],
    actions: [],
  },

  // Universal Connectors
  {
    id: 'web-search',
    name: 'Web Search',
    description: 'Live Tavily API search, DuckDuckGo web scraping & URL text extraction.',
    category: 'Developer Tools',
    icon: '/icons/search.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'search_web', name: 'Execute Web Search', description: 'Runs web search query.', type: 'action', inputs: [{ key: 'query', label: 'Search Query', type: 'string', required: true }], outputs: [{ key: 'results', label: 'Search Results', type: 'json', required: true }] }],
  },
  {
    id: 'http-request',
    name: 'HTTP Request Call',
    description: 'Send custom REST API GET, POST, PUT, or DELETE requests to any endpoint.',
    category: 'Developer Tools',
    icon: '/icons/webhook.svg',
    authType: 'none',
    triggers: [],
    actions: [{ id: 'custom_api_call', name: 'HTTP Request Call', description: 'Sends custom API call.', type: 'action', inputs: [{ key: 'url', label: 'API URL', type: 'string', required: true }], outputs: [{ key: 'statusCode', label: 'Status Code', type: 'number', required: true }] }],
  },
  {
    id: 'webhooks',
    name: 'Inbound Webhooks',
    description: 'Catch real-time HTTP POST webhooks from any external application.',
    category: 'Developer Tools',
    icon: '/icons/webhook.svg',
    authType: 'none',
    triggers: [{ id: 'catch_hook', name: 'Inbound Webhook Endpoint', description: 'Triggers on HTTP POST.', type: 'trigger', inputs: [], outputs: [{ key: 'body', label: 'Body Payload', type: 'json', required: true }] }],
    actions: [],
  },
  {
    id: 'rest-api',
    name: 'REST API Connector',
    description: 'Execute structured REST API calls with custom OAuth 2.0 or API Key authentication.',
    category: 'Developer Tools',
    icon: '/icons/globe.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'execute_rest', name: 'Execute REST API Call', description: 'Executes REST call.', type: 'action', inputs: [{ key: 'endpoint', label: 'Endpoint', type: 'string', required: true }], outputs: [{ key: 'data', label: 'Response Payload', type: 'json', required: true }] }],
  },
  {
    id: 'graphql',
    name: 'GraphQL Query Client',
    description: 'Execute custom GraphQL query and mutation requests with variable interpolation.',
    category: 'Developer Tools',
    icon: '/icons/code.svg',
    authType: 'api_key',
    triggers: [],
    actions: [{ id: 'query_graphql', name: 'Execute GraphQL Query', description: 'Runs GraphQL query.', type: 'action', inputs: [{ key: 'query', label: 'GraphQL Query', type: 'string', required: true }], outputs: [{ key: 'data', label: 'GraphQL Data', type: 'json', required: true }] }],
  },
  {
    id: 'autoflow-condition',
    name: 'If / Else Logic Condition',
    description: 'Split workflow execution paths into TRUE and FALSE branches based on rules.',
    category: 'Logic & Control Flow',
    icon: '/icons/condition.svg',
    authType: 'none',
    triggers: [],
    actions: [{ id: 'if_else', name: 'If / Else Rule Evaluation', description: 'Evaluates condition rule.', type: 'action', inputs: [{ key: 'leftValue', label: 'Test Value', type: 'string', required: true }], outputs: [{ key: 'matchedBranch', label: 'Matched Branch', type: 'string', required: true }] }],
  },
];
