import { BaseConnector } from '../core/base-connector';
import { ExecutionContext, ConnectorExecutionOutput } from '../core/types';
import { ConnectorManifest } from '@automation/shared-types';
import axios from 'axios';

export class TelegramConnector extends BaseConnector {
  manifest: ConnectorManifest = {
    id: 'telegram',
    name: 'Telegram Bot',
    description: 'Listen to inbound chat messages and send responses, alerts, and formatting via Telegram bots.',
    category: 'Messaging',
    icon: '/icons/telegram.svg',
    authType: 'api_key',
    triggers: [
      {
        id: 'new_message',
        name: 'New Message Received',
        description: 'Triggers when any contact or group sends a message to your Telegram Bot.',
        type: 'trigger',
        inputs: [
          { key: 'botToken', label: 'Telegram Bot Token (from @BotFather)', type: 'string', required: true },
        ],
        outputs: [
          { key: 'message_text', label: 'Message Text Content', type: 'string', required: true },
          { key: 'chat_id', label: 'Telegram Chat ID', type: 'number', required: true },
          { key: 'user_id', label: 'Sender User ID', type: 'number', required: true },
          { key: 'username', label: 'Sender Username', type: 'string', required: false },
          { key: 'first_name', label: 'First Name', type: 'string', required: false },
          { key: 'last_name', label: 'Last Name', type: 'string', required: false },
          { key: 'timestamp', label: 'Received Timestamp', type: 'string', required: true },
          { key: 'message_id', label: 'Message ID', type: 'number', required: true },
        ],
      },
    ],
    actions: [
      {
        id: 'send_message',
        name: 'Send Telegram Message',
        description: 'Sends a chat message, markdown alert, or automated response to a specified Telegram chat.',
        type: 'action',
        inputs: [
          { key: 'chat_id', label: 'Telegram Chat ID (e.g. {{trigger.chat_id}})', type: 'string', required: true },
          { key: 'message_text', label: 'Message Text (Supports Markdown/HTML)', type: 'string', required: true },
          { key: 'parse_mode', label: 'Formatting Mode (MarkdownV2, HTML, or Markdown)', type: 'string', required: false },
          { key: 'reply_to_message_id', label: 'Reply to Message ID (Optional)', type: 'string', required: false },
        ],
        outputs: [
          { key: 'message_id', label: 'Sent Message ID', type: 'number', required: true },
          { key: 'chat_id', label: 'Recipient Chat ID', type: 'number', required: true },
          { key: 'status', label: 'Delivery Status', type: 'string', required: true },
          { key: 'sent_at', label: 'Timestamp', type: 'string', required: true },
        ],
      },
    ],
  };

  async executeAction(actionId: string, context: ExecutionContext): Promise<ConnectorExecutionOutput> {
    const inputs = context.stepInput || {};
    const creds = context.connectionCredentials || {};
    const botToken = creds.apiKey || creds.botToken || inputs.botToken || process.env.TELEGRAM_BOT_TOKEN;

    // Default action handler for send_message, reply, or any dynamic action ID
    let chatId = inputs.chat_id || inputs.chatId;
    let text = inputs.message_text || inputs.text || inputs.message || inputs.content;
    const parseMode = inputs.parse_mode || inputs.parseMode || 'HTML';
    const replyTo = inputs.reply_to_message_id || inputs.replyToMessageId;

    // Robust context fallback for chatId
    if (!chatId || (typeof chatId === 'string' && (chatId.includes('{') || isNaN(Number(chatId))))) {
      const triggerData = context.workflowVariables?.trigger || context.workflowVariables?.triggerData || {};
      chatId = triggerData.chat_id || triggerData.chatId || triggerData.chat?.id;

      if (!chatId && context.workflowVariables) {
        for (const stepVal of Object.values(context.workflowVariables)) {
          if (stepVal?.output?.chat_id || stepVal?.output?.chatId || stepVal?.chat_id) {
            chatId = stepVal.output?.chat_id || stepVal.output?.chatId || stepVal?.chat_id;
            break;
          }
        }
      }
    }

    // Robust context fallback for text (generated by AI or upstream step)
    if (!text || (typeof text === 'string' && text.includes('{{') && text.includes('}}'))) {
      if (context.workflowVariables) {
        for (const stepVal of Object.values(context.workflowVariables)) {
          if (stepVal?.output?.text || stepVal?.output?.summary || stepVal?.output?.result || stepVal?.output?.message_text || stepVal?.output?.message) {
            text = stepVal.output?.text || stepVal.output?.summary || stepVal.output?.result || stepVal.output?.message_text || stepVal.output?.message;
            break;
          }
        }
      }
    }

    if (!chatId) {
      return {
        success: false,
        error: 'Missing required field: chat_id',
        data: {},
      };
    }

    if (!text) {
      text = '🤖 AutoFlow workflow step executed successfully!';
    }

    if (!botToken) {
      return {
        success: false,
        error: 'Telegram Bot Token is required to send messages.',
        data: {},
      };
    }

    try {
      const url = `https://api.telegram.org/bot${botToken}/sendMessage`;
      const payload: any = {
        chat_id: chatId,
        text,
        parse_mode: parseMode,
      };
      if (replyTo) payload.reply_to_message_id = replyTo;

      const res = await axios.post(url, payload, { timeout: 10000 });
      if (res.data && res.data.ok) {
        const msg = res.data.result;
        return {
          success: true,
          data: {
            message_id: msg.message_id,
            chat_id: msg.chat.id,
            status: 'sent',
            sent_at: new Date(msg.date * 1000).toISOString(),
          },
        };
      }
      return { success: false, error: res.data?.description || 'Telegram API request failed.', data: {} };
    } catch (err: any) {
      const errorMsg = err.response?.data?.description || err.message || 'Telegram API request failed';
      return { success: false, error: `Telegram API call error: ${errorMsg}`, data: {} };
    }
  }
}
